name: Summary CI
on:
  schedule:
    - cron: "0 0 * * *"
  repository_dispatch:
    types: [summary]
  workflow_dispatch:
jobs:
  release:
    name: Generate README
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "22"
      - uses: upptime/uptime-monitor@0b98676cda3ea664029aa354e4fab09d8b130f5f
        with:
          command: "readme"
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
